### ISSUE TITLE
flickr_api bugs

### ISSUE THREAD

**Issue by peterswang** [kencoken/imsearch-tools#6]
Tried query_demo.py with "num_results = 500" and "test_flickr_api=True". Failed with the following exceptions:
Executing Flickr API Search...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/flickr_api.py", line 49, in _fetch_results_from_offset
    num_results, self._results_per_req)
TypeError: not enough arguments for format string
<Greenlet at 0x106fd3410: <bound method FlickrAPISearch._fetch_results_from_offset of <imsearchtools.engines.flickr_api.FlickrAPISearch object at 0x105d8f590>>('hospital room', 0, aux_params={'sort': 'relevance', 'nojsoncallback': 1, 'format, num_results=500, headers={})> failed with TypeError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/flickr_api.py", line 49, in _fetch_results_from_offset
    num_results, self._results_per_req)
TypeError: not enough arguments for format string
<Greenlet at 0x106fd34b0: <bound method FlickrAPISearch._fetch_results_from_offset of <imsearchtools.engines.flickr_api.FlickrAPISearch object at 0x105d8f590>>('hospital room', 100, aux_params={'sort': 'relevance', 'nojsoncallback': 1, 'format, num_results=500, headers={})> failed with TypeError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/flickr_api.py", line 49, in _fetch_results_from_offset
    num_results, self._results_per_req)
TypeError: not enough arguments for format string
<Greenlet at 0x106fd3550: <bound method FlickrAPISearch._fetch_results_from_offset of <imsearchtools.engines.flickr_api.FlickrAPISearch object at 0x105d8f590>>('hospital room', 200, aux_params={'sort': 'relevance', 'nojsoncallback': 1, 'format, num_results=500, headers={})> failed with TypeError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/flickr_api.py", line 49, in _fetch_results_from_offset
    num_results, self._results_per_req)
TypeError: not enough arguments for format string
<Greenlet at 0x106fd35f0: <bound method FlickrAPISearch._fetch_results_from_offset of <imsearchtools.engines.flickr_api.FlickrAPISearch object at 0x105d8f590>>('hospital room', 300, aux_params={'sort': 'relevance', 'nojsoncallback': 1, 'format, num_results=500, headers={})> failed with TypeError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/flickr_api.py", line 49, in _fetch_results_from_offset
    num_results, self._results_per_req)
TypeError: not enough arguments for format string
<Greenlet at 0x106fd3730: <bound method FlickrAPISearch._fetch_results_from_offset of <imsearchtools.engines.flickr_api.FlickrAPISearch object at 0x105d8f590>>('hospital room', 400, aux_params={'sort': 'relevance', 'nojsoncallback': 1, 'format, num_results=500, headers={})> failed with TypeError

Traceback (most recent call last):
  File "query_demo.py", line 104, in <module>
    num_results=num_results)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/flickr_api.py", line 99, in query
    aux_params=aux_params)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/search_client.py", line 106, in _fetch_results
    raise QueryException("No image URLs could be retrieved")
imsearchtools.engines.search_client.QueryException: No image URLs could be retrieved

Looks line 49 of flickr_api.py needs an extra set of ().  Also, even with this fix, the current code doesn't allow more than self._results_per_req=100.  I.e. instead of checking
    if num_results > self._results_per_req:
and raising the exception, shouldn't there be a loop that cycles through all the pages instead?

**Comment by peterswang** [comment]
Re-running with num_results=100, query_demo.py failed with the following:
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 2403, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1794, in run
    launch(file, globals, locals)  # execute the script
  File "/Users/peterwang/PyProjects/wearva/web_images/query_demo.py", line 104, in <module>
    num_results=num_results)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/flickr_api.py", line 101, in query
    aux_params=aux_params)
  File "/Users/peterwang/PyProjects/wearva/web_images/imsearchtools/engines/search_client.py", line 106, in _fetch_results
    raise QueryException("No image URLs could be retrieved")
imsearchtools.engines.search_client.QueryException: No image URLs could be retrieved

Putting breakpoint in _fetch_results_from_offset() in flickr_api.py and stepping through, the HTTP response code was 403. Both the Flickr API and secret are populated in api_credential.py. But, didn't see FLICKR_API_SECRET being used.

**Comment by kostyaev** [comment]
Made a pull request #7 with a change to flickr api endpoint, it will fix the problem mentioned above. FLICKR_API_SECRET is not required for [ flickr.photos.search](https://www.flickr.com/services/api/flickr.photos.search.html)

**Comment by kencoken** [comment]
Thanks for the assistance kostyaev – have merged the PR!
